# fly.toml app configuration file generated for raresroca05-pennylane-yem-2a

app = 'raresroca05-pennylane-yem-2a'
primary_region = 'ams'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  PORT = '3000'
  RAILS_ENV = 'production'
  RAILS_SERVE_STATIC_FILES = 'true'
  RAILS_LOG_TO_STDOUT = 'true'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = './bin/rails server'
  
[mounts] 